#!/bin/bash

usage="Usage: $0 source_dir dest_dir base_namespace"

if [ "$1" == "" ]; then
    echo $usage
    exit 1
fi

if [ "$2" == "" ]; then
    echo $usage
    exit 1
fi

if [ "$3" == "" ]; then
    echo $usage
    exit 1
fi

if [ ! "$4" == "" ]; then
    echo $usage
    exit 1
fi

python -tt "$(dirname "$0")"/src/main.py "$1" "$2" "$3"

